# Generated by Django 4.1.5 on 2023-01-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='url_title',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='url_title',
        ),
        migrations.AddField(
            model_name='productbrand',
            name='slug',
            field=models.SlugField(default='', max_length=300, verbose_name='نام در url'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default='', verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brands', to='product_module.productbrand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_gallery', to='product_module.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productvisit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_visit', to='product_module.product', verbose_name='محصول'),
        ),
    ]
