# Generated by Django 4.1.5 on 2023-01-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='slug',
        ),
        migrations.AddField(
            model_name='productbrand',
            name='english_title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=300, null=True, verbose_name='نام در url'),
        ),
    ]
