# Generated by Django 4.1.5 on 2023-01-08 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_module', '0006_remove_productbrand_slug_productbrand_english_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commend_text', models.TextField(verbose_name='متن کامنت')),
                ('commend_mode', models.CharField(choices=[('Poker', 'پوکر'), ('Good', 'خوب'), ('Bad', 'بد')], max_length=50, verbose_name='مود کامنت')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='برای محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
