# Generated by Django 4.1.5 on 2023-01-09 12:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_module', '0007_productcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='commend_mode',
            field=models.CharField(choices=[('Poker', 'پوکر'), ('Bad', 'بد'), ('Good', 'خوب')], max_length=50, verbose_name='مود کامنت'),
        ),
        migrations.CreateModel(
            name='ProductVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5, 'نمیتوانید بیشتر از 5 امتیاز برای محصول ثبت کنید'), django.core.validators.MinValueValidator(1, 'نمیتوانید کمتر از 1 امتیاز برای محصول ثبت کنید')], verbose_name='امتیاز')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='مربوط به محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر رای دهنده')),
            ],
            options={
                'verbose_name': 'امتیاز محصول',
                'verbose_name_plural': 'امتیازات محصول',
            },
        ),
    ]
