# Generated by Django 4.1.5 on 2023-01-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_alter_productcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='commend_mode',
            field=models.CharField(choices=[('Poker', 'پوکر'), ('Good', 'خوب'), ('Bad', 'بد')], max_length=50, verbose_name='مود کامنت'),
        ),
    ]
