# Generated by Django 4.1.5 on 2023-01-14 15:14

from django.db import migrations, models
import product_module.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0017_alter_productcomment_commend_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.CharField(help_text='حتما از علامت (٪) در اخر استفاده کنید', max_length=4, validators=[product_module.validators.valid_pct], verbose_name='درصد تخفیف')),
                ('discount_price', models.PositiveIntegerField(verbose_name='مقدار قیمتی تخفیف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('expires_date', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('discount_type', models.CharField(choices=[('Percent', 'درصدی'), ('Price', 'قیمتی')], max_length=8, verbose_name='نوع کوپن')),
            ],
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='commend_mode',
            field=models.CharField(choices=[('Bad', 'بد'), ('Poker', 'پوکر'), ('Good', 'خوب')], max_length=50, verbose_name='مود کامنت'),
        ),
    ]
