# Generated by Django 4.1.5 on 2023-01-14 15:38

from django.db import migrations, models
import product_module.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0019_alter_productcoupon_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcoupon',
            name='coupon_code',
            field=models.CharField(default='amir', max_length=10, validators=[product_module.validators.coupon_code_validator], verbose_name='کد کوپن'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='commend_mode',
            field=models.CharField(choices=[('Bad', 'بد'), ('Good', 'خوب'), ('Poker', 'پوکر')], max_length=50, verbose_name='مود کامنت'),
        ),
    ]
