# Generated by Django 4.1.5 on 2023-01-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0021_alter_productcomment_commend_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', max_length=200, null=True, unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', null=True, unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='commend_mode',
            field=models.CharField(choices=[('Poker', 'پوکر'), ('Bad', 'بد'), ('Good', 'خوب')], max_length=50, verbose_name='مود کامنت'),
        ),
    ]
