# Generated by Django 4.1.5 on 2023-01-16 09:41

import django.core.validators
from django.db import migrations, models
import product_module.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0022_alter_product_slug_alter_productcategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='commend_mode',
            field=models.CharField(choices=[('Poker', 'پوکر'), ('Good', 'خوب'), ('Bad', 'بد')], max_length=50, verbose_name='مود کامنت'),
        ),
        migrations.AlterField(
            model_name='productcoupon',
            name='coupon_code',
            field=models.CharField(db_index=True, max_length=10, validators=[product_module.validators.coupon_code_validator], verbose_name='کد کوپن'),
        ),
        migrations.AlterField(
            model_name='productcoupon',
            name='discount_type',
            field=models.CharField(choices=[('Price', 'قیمتی'), ('Percent', 'درصدی')], max_length=8, verbose_name='نوع کوپن'),
        ),
        migrations.AlterField(
            model_name='productvote',
            name='vote',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(5, 'نمیتوانید بیشتر از 5 امتیاز برای محصول ثبت کنید'), django.core.validators.MinValueValidator(1, 'نمیتوانید کمتر از 1 امتیاز برای محصول ثبت کنید')], verbose_name='امتیاز'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
