# Generated by Django 4.1.5 on 2023-03-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0023_alter_productcomment_commend_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='commend_mode',
            field=models.CharField(choices=[('Good', 'خوب'), ('Poker', 'پوکر'), ('Bad', 'بد')], max_length=50, verbose_name='مود کامنت'),
        ),
        migrations.AlterField(
            model_name='productcoupon',
            name='discount_type',
            field=models.CharField(choices=[('Percent', 'درصدی'), ('Price', 'قیمتی')], max_length=8, verbose_name='نوع کوپن'),
        ),
    ]
