# Generated by Django 4.1.5 on 2023-03-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0025_alter_productcomment_commend_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcoupon',
            name='discount_type',
            field=models.CharField(choices=[('Price', 'قیمتی'), ('Percent', 'درصدی')], max_length=8, verbose_name='نوع کوپن'),
        ),
    ]
