# Generated by Django 4.1.5 on 2023-04-02 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0033_alter_productcomment_commend_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='commend_mode',
            field=models.CharField(choices=[('Good', 'خوب'), ('Bad', 'بد'), ('Poker', 'پوکر')], max_length=50, verbose_name='مود کامنت'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_categories', to='product_module.productcategory', verbose_name='دسته بندی ها'),
        ),
    ]
