# Generated by Django 4.1.5 on 2023-01-11 09:50

from django.db import migrations, models
import order_module.validators


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0005_alter_orderdetail_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='count',
            field=models.IntegerField(validators=[order_module.validators.min_count_validator], verbose_name='تعداد'),
        ),
    ]
