# Generated by Django 4.1.5 on 2023-01-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0021_alter_productcomment_commend_mode_and_more'),
        ('order_module', '0007_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_module.productcoupon', verbose_name='تخفیف'),
        ),
    ]
