# Generated by Django 4.1.5 on 2023-03-25 08:02

from django.db import migrations, models
import django.db.models.deletion
import order_module.validators


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_alter_city_options_alter_province_options'),
        ('order_module', '0009_shipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'verbose_name': 'مشخصات تحویل گیرنده', 'verbose_name_plural': 'مشخصات تحویل گیرندگان'},
        ),
        migrations.AddField(
            model_name='order',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_module.shipment', verbose_name='اطلاعات تحویل'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='address',
            field=models.TextField(default='hesarach', verbose_name='آدرس پستی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='building_unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='واحد خونه'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='site_module.city', verbose_name='شهر مقصد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='house_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پلاک خونه'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='national_code',
            field=models.CharField(default='0313304300', max_length=255, validators=[order_module.validators.is_valid_iran_code], verbose_name='کد ملی گیرنده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='phone_number',
            field=models.CharField(default='09302483540', max_length=255, validators=[order_module.validators.is_valid_phone_number], verbose_name='شماره تماس گیرنده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='postal_code',
            field=models.CharField(default='3177648147', max_length=255, validators=[order_module.validators.is_valid_postal_code], verbose_name='کد پستی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='site_module.province', verbose_name='استان مقصد'),
            preserve_default=False,
        ),
    ]
