# Generated by Django 4.1.5 on 2023-03-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_alter_city_name_alter_province_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهر ها'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'استان', 'verbose_name_plural': 'استان ها'},
        ),
    ]
