# Generated by Django 4.1.5 on 2023-01-07 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان پاسخ')),
                ('message', models.TextField(verbose_name='متن پاسخ')),
                ('is_answered', models.BooleanField(default=True, verbose_name='پاسخ داده شده')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_us_response', to='contact_module.contactus', verbose_name='مربوط به پیام')),
            ],
            options={
                'verbose_name': 'پاسخ پیام',
                'verbose_name_plural': 'پاسخ های پیام',
            },
        ),
    ]
